import { images } from '../images';

const {
  technicalWizardryOfOurWebDesignAgencyImage,
  blogs13Image,
  strategiesForEffectiveWebDesignByOurAgencyImage,
  howAgecisPutsYourAudienceFirstInEveryWebsiteProject,
  ensuresYourWebsiteRisesToTheTopOfSearchRankingsImage,
} = images;
export const blogPosts = [
  
    {
        "id": 1,
        "image": blogs13Image,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Digital Marketing",
        "comments": 3,
        "heading": "How to Use Chatbots to Improve Customer Service and Engagement ?",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-use-chatbots-to-improve-customer-service-and-engagement/",
        "author": "Tech SaraZ"
    },
    {
        "id": 2,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Social Media Marketing",
        "comments": 3,
        "heading": "How to Find and Work with Influencers to Promote Your Brand ?",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-find-and-work-with-influencers-to-promote-your-brand/",
        "author": "Tech SaraZ"
    },
    {
        "id": 3,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Digital Marketing",
        "comments": 3,
        "heading": "The Future of Digital Marketing: Predictions for 2024 and Beyond",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-future-of-digital-marketing-predictions-for-2024-and-beyond/",
        "author": "Tech SaraZ"
    },
    {
        "id": 4,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Digital Marketing",
        "comments": 3,
        "heading": "How to build a successful digital marketing strategy from scratch?",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-build-a-successful-digital-marketing-strategy-from-scratch/",
        "author": "Tech SaraZ"
    },
    {
        "id": 5,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Social Media Marketing",
        "comments": 3,
        "heading": "10 tips for creating a successful social media marketing campaign",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/10-tips-for-creating-a-successful-social-media-marketing-campaign/",
        "author": "Tech SaraZ"
    },
    {
        "id": 6,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Search Engine Optimization.",
        "comments": 3,
        "heading": "The Importance of SEO and How to Optimize Your Website for Search Engines",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-importance-of-seo-and-how-to-optimize-your-website-for-search-engines/",
        "author": "Tech SaraZ"
    },
    {
        "id": 7,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "How a good web design can help your business grow in Bangalore?",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-a-good-web-design-can-help-your-business-grow-in-bangalore/",
        "author": "Tech SaraZ"
    },
    {
        "id": 8,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "Latest Trends in Web Designing Services in Bangalore",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/latest-trends-in-web-designing-services-in-bangalore/",
        "author": "Tech SaraZ"
    },
    {
        "id": 9,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Digital Marketing",
        "comments": 3,
        "heading": "The Importance of Data Privacy in Digital Marketing",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-importance-of-data-privacy-in-digital-marketing/",
        "author": "Tech SaraZ"
    },
    {
        "id": 10,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Digital Marketing",
        "comments": 3,
        "heading": "The Role of AI in Transforming Digital Marketing",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-role-of-ai-in-transforming-digital-marketing/",
        "author": "Tech SaraZ"
    },
    {
        "id": 11,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "Top 10 Web Development Companies in Hyderabad for 2024",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/top-10-web-development-companies-in-hyderabad-for-2024/",
        "author": "Tech SaraZ"
    },
    {
        "id": 12,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "Why Your Business Needs a Professionally Designed Website",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/why-your-business-needs-a-professionally-designed-website/",
        "author": "Tech SaraZ"
    },
    {
        "id": 13,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "10 Common Web Design Mistakes to Avoid",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/10-common-web-design-mistakes-to-avoid/",
        "author": "Tech SaraZ"
    },
    {
        "id": 14,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "The Importance of Color Theory in Web Design",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-importance-of-color-theory-in-web-design/",
        "author": "Tech SaraZ"
    },
    {
        "id": 15,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "The Importance of an SEO-Friendly URL Structure for Businesses",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-importance-of-an-seo-friendly-url-structure-for-businesses/",
        "author": "Tech SaraZ"
    },
    {
        "id": 16,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "Top 10 Tools for Web Designers in 2024",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/top-10-tools-for-web-designers-in-2024/",
        "author": "Tech SaraZ"
    },
    {
        "id": 17,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "The role of AI in WordPress development",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-role-of-ai-in-wordpress-development/",
        "author": "Tech SaraZ"
    },
    {
        "id": 18,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Search Engine Optimization.",
        "comments": 3,
        "heading": "How to Dominate Local SEO Search Rankings in 2024",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-dominate-local-seo-search-rankings-in-2023/",
        "author": "Tech SaraZ"
    },
    {
        "id": 19,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "How to Protect a WordPress Website from Hackers?",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-protect-a-wordpress-website-from-hackers/",
        "author": "Tech SaraZ"
    },
    {
        "id": 20,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "How to Choose the Best Web Development Company?",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-choose-the-best-web-development-company/",
        "author": "Tech SaraZ"
    },
    {
        "id": 21,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "How to Use Chatbots to Improve Customer Service and Engagement (3)",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-find-and-work-with-influencers-to-promote-your-brand/how-to-use-chatbots-to-improve-customer-service-and-engagement-3/",
        "author": "Tech SaraZ"
    },
    {
        "id": 22,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "How to Use Chatbots to Improve Customer Service and Engagement (2)",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-use-chatbots-to-improve-customer-service-and-engagement/how-to-use-chatbots-to-improve-customer-service-and-engagement-2/",
        "author": "Tech SaraZ"
    },
    {
        "id": 23,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "The Future of Digital Marketing",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-future-of-digital-marketing-predictions-for-2024-and-beyond/the-future-of-digital-marketing/",
        "author": "Tech SaraZ"
    },
    {
        "id": 24,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Digital Marketing strategy from scratch",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-build-a-successful-digital-marketing-strategy-from-scratch/digital-marketing-strategy-from-scratch/",
        "author": "Tech SaraZ"
    },
    {
        "id": 25,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "social media marketing campaign",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/10-tips-for-creating-a-successful-social-media-marketing-campaign/social-media-marketing-campaign/",
        "author": "Tech SaraZ"
    },
    {
        "id": 26,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "The Importance of SEO and How to Optimize Your Website for Search Engines",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-importance-of-seo-and-how-to-optimize-your-website-for-search-engines/the-importance-of-seo-and-how-to-optimize-your-website-for-search-engines-2/",
        "author": "Tech SaraZ"
    },
    {
        "id": 27,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Business grow in bangalore",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-a-good-web-design-can-help-your-business-grow-in-bangalore/how-a-good-web-design-can-help-your-business-grow-in-bangalore-2/",
        "author": "Tech SaraZ"
    },
    {
        "id": 28,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Lastest web designing trands in Bengaluru",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/latest-trends-in-web-designing-services-in-bangalore/lastest-web-designing-trands-in-bengaluru/",
        "author": "Tech SaraZ"
    },
    {
        "id": 29,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "The Importance of Data Privacy in Digital Marketing",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-importance-of-data-privacy-in-digital-marketing/the-importance-of-data-privacy-in-digital-marketing/",
        "author": "Tech SaraZ"
    },
    {
        "id": 30,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "How to Use Chatbots to Improve Customer Service and Engagement",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-role-of-ai-in-transforming-digital-marketing/how-to-use-chatbots-to-improve-customer-service-and-engagement-4/",
        "author": "Tech SaraZ"
    },
    {
        "id": 31,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Social Media Marketing",
        "comments": 3,
        "heading": "Building a Powerful Brand Identity: Digital Marketing Insights",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/building-a-powerful-brand-identity-digital-marketing-insights/",
        "author": "Tech SaraZ"
    },
    {
        "id": 32,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "WordPress vs Custom website",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/wordpress-vs-custom-website/",
        "author": "Tech SaraZ"
    },
    {
        "id": 33,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Uncategorized",
        "comments": 3,
        "heading": "Web designing – The best way to create professional websites",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/web-designing-the-best-way-to-create-professional-websites/",
        "author": "Tech SaraZ"
    },
    {
        "id": 34,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Search Engine Optimization.",
        "comments": 3,
        "heading": "Search engine optimization - Key to handle the web traffic",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/search-engine-optimization-key-to-handle-the-web-traffic/",
        "author": "Tech SaraZ"
    },
    {
        "id": 35,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Digital Marketing",
        "comments": 3,
        "heading": "Digital marketing – The best way to elevate your brand and online presence",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/digital-marketing-the-best-way-to-elevate-your-brand-and-online-presence/",
        "author": "Tech SaraZ"
    },
    {
        "id": 36,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "The ultimate guide for choosing the professional web designing firm",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-ultimate-guide-for-choosing-the-professional-web-designing-firm/",
        "author": "Tech SaraZ"
    },
    {
        "id": 37,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Web Designing",
        "comments": 3,
        "heading": "Web designing - Unlock the latest features for your website",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/web-designing-unlock-the-latest-features-for-your-website/",
        "author": "Tech SaraZ"
    },
    {
        "id": 38,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "Digital Marketing",
        "comments": 3,
        "heading": "Clever strategy to maximize your reach",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/clever-strategy-to-maximize-your-reach/",
        "author": "Tech SaraZ"
    },
    {
        "id": 39,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Top WordPress Website Development Company in Bangalore: Elevate Your Online Presence",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/top-wordpress-website-development-company-in-bangalore-elevate-your-online-presence/",
        "author": "Tech SaraZ"
    },
    {
        "id": 40,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Web Development Company in JP Nagar, Bangalore: Elevate Your Online Presence",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/web-development-company-in-jp-nagar-bangalore-elevate-your-online-presence/",
        "author": "Tech SaraZ"
    },
    {
        "id": 41,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Top 10 Web Development Companies in Hyderabad for 2023",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/top-10-web-development-companies-in-hyderabad-for-2024/top-10-web-development-companies-in-hyderabad-for-2023/",
        "author": "Tech SaraZ"
    },
    {
        "id": 42,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Why Your Business Needs a Professionally Designed Website",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/why-your-business-needs-a-professionally-designed-website/why-your-business-needs-a-professionally-designed-website/",
        "author": "Tech SaraZ"
    },
    {
        "id": 43,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "10 Common Web Design Mistakes to Avoid",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/10-common-web-design-mistakes-to-avoid/10-common-web-design-mistakes-to-avoid/",
        "author": "Tech SaraZ"
    },
    {
        "id": 44,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "The Importance of Color Theory in Web Design",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-importance-of-color-theory-in-web-design/the-importance-of-color-theory-in-web-design/",
        "author": "Tech SaraZ"
    },
    {
        "id": 45,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "The Importance of an SEO-Friendly URL Structure for Businesses",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-importance-of-an-seo-friendly-url-structure-for-businesses/the-importance-of-an-seo-friendly-url-structure-for-businesses/",
        "author": "Tech SaraZ"
    },
    {
        "id": 46,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Tools for Web Designers",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/top-10-tools-for-web-designers-in-2024/top-10-tools-for-web-designers/",
        "author": "Tech SaraZ"
    },
    {
        "id": 47,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "The role of Ai in Wordpress Development",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-role-of-ai-in-wordpress-development/the-role-of-ai-in-wordpress-development/",
        "author": "Tech SaraZ"
    },
    {
        "id": 48,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "How to Dominate Local SEO Search Rankings in 2023",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-dominate-local-seo-search-rankings-in-2023/how-to-dominate-local-seo-search-rankings-in-2023-2/",
        "author": "Tech SaraZ"
    },
    {
        "id": 49,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "How to Protect a WordPress Website from Hackers",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-protect-a-wordpress-website-from-hackers/how-to-protect-a-wordpress-website-from-hackers/",
        "author": "Tech SaraZ"
    },
    {
        "id": 50,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "How to choose the Best web development Company",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-choose-the-best-web-development-company/how-to-choose-the-best-web-development-company/",
        "author": "Tech SaraZ"
    },
    {
        "id": 51,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Building a Powerful Brand Identity Digital Marketing Insights",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/building-a-powerful-brand-identity-digital-marketing-insights/building-a-powerful-brand-identity-digital-marketing-insights/",
        "author": "Tech SaraZ"
    },
    {
        "id": 52,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Top 10 Web Development Companies in Hyderabad for 2024",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/top-10-web-development-companies-in-hyderabad-for-2024/",
        "author": "Tech SaraZ"
    },
    {
        "id": 53,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "How to Dominate Local SEO Search Rankings in 2024",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/how-to-dominate-local-seo-search-rankings-in-2024/",
        "author": "Tech SaraZ"
    },
    {
        "id": 54,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Top 10 Tools for Web Designers in 2024",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/top-10-tools-for-web-designers-in-2024/",
        "author": "Tech SaraZ"
    },
    {
        "id": 55,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "WordPress vs Custom website",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/building-a-powerful-brand-identity-digital-marketing-insights/wordpress-vs-custom-website/",
        "author": "Tech SaraZ"
    },
    {
        "id": 56,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Web designing – The best way to create professional websites",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/web-designing-the-best-way-to-create-professional-websites/web-designing-the-best-way-to-create-professional-websites-2/",
        "author": "Tech SaraZ"
    },
    {
        "id": 57,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Search engine optimization - Key to handle the web traffic1",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/search-engine-optimization-key-to-handle-the-web-traffic/search-engine-optimization-key-to-handle-the-web-traffic1/",
        "author": "Tech SaraZ"
    },
    {
        "id": 58,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Digital marketing – The best way to elevate your brand and online presence",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/digital-marketing-the-best-way-to-elevate-your-brand-and-online-presence/digital-marketing-the-best-way-to-elevate-your-brand-and-online-presence/",
        "author": "Tech SaraZ"
    },
    {
        "id": 59,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "42408",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/the-ultimate-guide-for-choosing-the-professional-web-designing-firm/attachment/42408/",
        "author": "Tech SaraZ"
    },
    {
        "id": 60,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Web designing - Unlock the latest features for your website",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/web-designing-unlock-the-latest-features-for-your-website/web-designing-unlock-the-latest-features-for-your-website/",
        "author": "Tech SaraZ"
    },
    {
        "id": 61,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "cover",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/clever-strategy-to-maximize-your-reach/cover/",
        "author": "Tech SaraZ"
    },
    {
        "id": 62,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "IMG-20240921-WA0006",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/top-wordpress-website-development-company-in-bangalore-elevate-your-online-presence/img-20240921-wa0006/",
        "author": "Tech SaraZ"
    },
    {
        "id": 63,
        "image": technicalWizardryOfOurWebDesignAgencyImage,
        "date": "Fri, 17 Jan 2025 07:02:02 +0000",
        "categorie": "",
        "comments": 3,
        "heading": "Capture",
        "summary": "Summary",
        "paragraph": "Paragraph",
        "readMoreLink": "https://staging.edutechsaraz.com/web-development-company-in-jp-nagar-bangalore-elevate-your-online-presence/capture/",
        "author": "Tech SaraZ"
    }

  // {
  //   id: 1,
  //   image: technicalWizardryOfOurWebDesignAgencyImage,
  //   author: 'Tech SaraZ',
  //   date: 'February 13, 2023',
  //   comments: 3,
  //   heading: 'Technical Wizardry Of Our Web Design Agency',
  //   paragraph:
  //     'Strategies for Effective Web Design by Our Agency. In the dynamic world of web design, where first impressions are currency and user experience reigns supreme, our agency has honed a repertoire of strategies that redefine digital landscapes...',
  //   readMoreLink: '/blog/technical-wizardry',
  //   categorie: 'Business Solution'
  // },
  // {
  //   id: 7,
  //   image: technicalWizardryOfOurWebDesignAgencyImage,
  //   author: 'Tech SaraZ',
  //   date: 'February 13, 2023',
  //   comments: 3,
  //   heading: 'Technical Wizardry Of Our Web Design Agency2',
  //   paragraph:
  //     'Strategies for Effective Web Design by Our Agency. In the dynamic world of web design, where first impressions are currency and user experience reigns supreme, our agency has honed a repertoire of strategies that redefine digital landscapes...',
  //   readMoreLink: '/blog/technical-wizardry',
  //   categorie: 'Business Solution'
  // },
  // {
  //   id: 2,
  //   image: blogs13Image, // Another blog image
  //   author: 'Tech SaraZ',
  //   date: 'March 5, 2023',
  //   comments: 5,
  //   heading: 'How to Create Beautiful UI Designs',
  //   paragraph:
  //     'UI design is crucial to enhancing user experience. In this post, we explore the best practices for designing intuitive and engaging user interfaces that captivate users...',
  //   readMoreLink: '/blog/how-to-create-beautiful-ui-designs',
  //   categorie: 'Content Strategy'
  // },
  // {
  //   id: 3,
  //   image: blogs13Image, // Another blog image
  //   author: 'Tech SaraZ',
  //   date: 'March 5, 2023',
  //   comments: 5,
  //   heading: 'How to Create Beautiful UI Designs',
  //   paragraph:
  //     'UI design is crucial to enhancing user experience. In this post, we explore the best practices for designing intuitive and engaging user interfaces that captivate users...',
  //   readMoreLink: '/blog/how-to-create-beautiful-ui-designs',
  //   categorie: 'Digital Marketing'
  // },
  // {
  //   id: 4,
  //   image: blogs13Image, // Another blog image
  //   author: 'Tech SaraZ',
  //   date: 'March 5, 2023',
  //   comments: 5,
  //   heading: 'How to Create Beautiful UI Designs',
  //   paragraph:
  //     'UI design is crucial to enhancing user experience. In this post, we explore the best practices for designing intuitive and engaging user interfaces that captivate users...',
  //   readMoreLink: '/blog/how-to-create-beautiful-ui-designs',
  //   categorie: 'Software Design'
  // },
  // {
  //   id: 5,
  //   image: blogs13Image, // Another blog image
  //   author: 'Tech SaraZ',
  //   date: 'March 5, 2023',
  //   comments: 5,
  //   heading: 'How to Create Beautiful UI Designs',
  //   paragraph:
  //     'UI design is crucial to enhancing user experience. In this post, we explore the best practices for designing intuitive and engaging user interfaces that captivate users...',
  //   readMoreLink: '/blog/how-to-create-beautiful-ui-designs',
  //   categorie: 'Technology'
  // },
  // {
  //   id: 6,
  //   image: blogs13Image, // Another blog image
  //   author: 'Tech SaraZ',
  //   date: 'March 5, 2023',
  //   comments: 5,
  //   heading: 'How to Create Beautiful UI Designs',
  //   paragraph:
  //     'UI design is crucial to enhancing user experience. In this post, we explore the best practices for designing intuitive and engaging user interfaces that captivate users...',
  //   readMoreLink: '/blog/how-to-create-beautiful-ui-designs',
  //   categorie: 'Web Development'
  // },
  // Add more blog posts as needed
];

export const blogCategories = [
  { name: 'Business Solution', link: '/category/business-solution' },
  { name: 'Content Strategy', link: '/category/content-strategy' },
  { name: 'Digital Marketing', link: '/category/digital-marketing' },
  { name: 'Software Design', link: '/category/software-design' },
  { name: 'Technology', link: '/category/technology' },
  { name: 'Web Development', link: '/category/web-development' },
];

export const blogRecentPosts = [
  {
    image: howAgecisPutsYourAudienceFirstInEveryWebsiteProject,
    author: 'Tech SaraZ',
    heading: 'HOW AGECIS PUTS YOUR AUDIENCE',
    link: '/post/how-agecis-puts-your-audience',
  },
  {
    image: ensuresYourWebsiteRisesToTheTopOfSearchRankingsImage,
    author: 'Tech SaraZ',
    heading: 'ENSURES YOUR WEBSITE RISES TO',
    link: '/post/ensures-your-website-rises-to',
  },
  {
    image: strategiesForEffectiveWebDesignByOurAgencyImage,
    author: 'Tech SaraZ',
    heading: 'STRATEGIES FOR EFFECTIVE WEB DESIGN',
    link: '/post/strategies-for-effective-web-design',
  },
];

export const blogTags = [
  { name: 'Analytics', link: '/tag/analytics' },
  { name: 'Apps', link: '/tag/apps' },
  { name: 'Design', link: '/tag/design' },
  { name: 'Development', link: '/tag/development' },
  { name: 'Figma', link: '/tag/figma' },
  { name: 'Marketing', link: '/tag/marketing' },
  { name: 'Photoshop', link: '/tag/photoshop' },
  { name: 'Repair', link: '/tag/repair' },
  { name: 'SEO', link: '/tag/seo' },
  { name: 'Technology', link: '/tag/technology' },
];
