import { images } from '../images';

const {
  blogWriting768x587Image,
  writingImage,
  webContentWriting768x587Image,
  contentwritingImage,
  markeitngMaterialContentWriting768x587Image,
  contentMarketing1Image,
  socialMediaContentWriting768x587Image,
  socialMediaManagementImage,
  logoDesigning768x587Image,
  webDesigning768x587Image,
  artImage,
  advertisingDesign768x587Image,
  brandingImage,
  brandingDesigning768x587Image,
  branding1Image,
  businessAndMarketingDesign768x587Image,
  renameImage,
  designtoolImage,
} = images;
export const serviceContentConfig = [
  {
    id: 1,
    title: 'Blog Writing Services Bangalore',
    description: [
      'Tech Saraz specializes in delivering intriguing, SEO-friendly blog writing services, particularly for businesses in Bangalore.',
      'Our talented team crafts top-notch blogs that don’t just captivate your audience but also drive more traffic to your site. We offer creative and well-researched content tailored to your niche, ensuring enhanced online visibility and increased user engagement.',
    ],
    imageSrc: blogWriting768x587Image,
    altText: 'Blog Writing',
    points: [
      'Seo Friendly',
      'Authority and Credibility',
      'Leads and conversions',
      'Customer Loyalty',
      'Long term Results',
    ],
    pulseImageSrc: writingImage,
    pulseAltText: 'Writing Pulse',
  },
  {
    id: 2,
    title: 'Website Content Writing Bangalore',
    description: [
      'At Tech Saraz, we understand the value of engaging website content writing services in Bangalore for your business.',
      'Our skilled team takes pride in crafting compelling and persuasive narratives for your website, keeping visitors hooked while effectively communicating your brand’s message. Rely on us for high-quality, SEO-optimized content that helps improve your digital footprint, especially in Bangalore’s competitive market.',
    ],
    imageSrc: webContentWriting768x587Image,
    altText: 'Website Content Writing',
    points: [
      'Relevant content',
      'Up to date Seo Practices',
      'Brand Awareness',
      'High sales and conversion Rates',
    ],
    pulseImageSrc: contentwritingImage,
    pulseAltText: 'Content Writing Pulse',
  },
  {
    id: 3,
    title: 'Marketing Material Content Services Bangalore',
    description: [
      'Tech Saraz offers stellar content writing for marketing materials. We create persuasive narratives for brochures, flyers, newsletters, and more that reflect your brand’s identity.',
      'Our content is engaging and designed to meet your marketing objectives effectively. Trust us to deliver content that resonates with your audience and amplifies your brand’s reach.',
    ],
    imageSrc: markeitngMaterialContentWriting768x587Image,
    altText: 'Marketing Material Writing',
    points: [
      'Target pain points and desires.',
      'Enhance visibility',
      'Brand Awareness',
      'Save Time and Money',
    ],
    pulseImageSrc: contentMarketing1Image,
    pulseAltText: 'Marketing Pulse',
  },
  {
    id: 4,
    title: 'Social Media Content Writing Bangalore',
    description: [
      'Capitalizing on the power of social media, Tech Saraz crafts engaging content that optimizes your brand’s presence on various platforms.',
      'We design content that syncs with the latest trends, encourages user interaction, and drives traffic to your site. With our specialized social media content writing services in Bangalore, make your mark in the digital world, especially among businesses in Bangalore.',
    ],
    imageSrc: socialMediaContentWriting768x587Image,
    altText: 'Social Media Content Writing',
    points: [
      'Improves customer retention',
      'Enhances customer engagement',
      'Expands customer reach',
      'Cost-effective solution',
    ],
    pulseImageSrc: socialMediaManagementImage,
    pulseAltText: 'Social Media Pulse',
  },
];

export const serviceGraphicsDesignConfig = [
  {
    id: 1,
    title: 'Logo Design Services in Bangalore',
    description: [
      'Our strategic process begins with an in-depth analysis of your business model, a clear understanding of your objectives, and a thorough assessment of your users’ needs.',
      'Leveraging these insights, we craft a UX strategy that captivates your audience, driving user engagement and conversions and positioning us as a leading provider of UX design in Bangalore.',
    ],
    imageSrc: logoDesigning768x587Image,
    altText: 'Logo Design Image',
    points: [
      'Establishes brand identity',
      'Differentiates from competitors',
      'Conveys professionalism',
      'Boosts marketing efforts',
    ],
    pulseImageSrc: designtoolImage,
    pulseAltText: 'Design Pulse',
  },
  {
    id: 2,
    title: 'Web Designing Services in Bangalore',
    description: [
      'Your website is your digital storefront, and at Tech Saraz, we are dedicated to designing visually attractive, user-friendly, and responsive websites.',
      'Our Bangalore-based team collaborates with you to build a website that mirrors your brand’s identity and engages your audience effectively. Trust Tech Saraz, a leading graphics designing company in Bangalore, for a website that transcends being a mere digital presence to become a potent marketing tool.',
    ],
    imageSrc: webDesigning768x587Image,
    altText: 'Web Designing Image',
    points: [
      'Search engine visibility',
      'Build trust with visitors',
      'Brand image',
      'Responsive design',
    ],
    pulseImageSrc: artImage,
    pulseAltText: 'Art Pulse',
  },
  {
    id: 3,
    title: 'Advertising Design Services in Bangalore',
    description: [
      'Our team of expert designers at Tech Saraz excels at creating visually stunning and intuitive interfaces. We prioritize optimizing user interaction, crafting designs that consistently reflect your brand’s image, and fostering user loyalty.',
      'Our commitment to these principles makes us a go-to for UI design in Bangalore.',
    ],
    imageSrc: advertisingDesign768x587Image,
    altText: 'Advertising Design Image',
    points: [
      'Professionalism and expertise',
      'Consistency in branding',
      'Attention-grabbing designs',
      'Increased ROI',
    ],
    pulseImageSrc: brandingImage,
    pulseAltText: 'Branding Pulse',
  },
  {
    id: 4,
    title: 'Branding Designing Services in Bangalore',
    description: [
      'Tech Saraz is committed to helping you create a unique identity for your brand through our branding designing services.',
      'Our Bangalore-based team collaborates with you to understand your brand’s values and personality, translating them into a design that sets you apart. With Tech Saraz, a premier graphics designing company in Bangalore, you can expect a brand design that genuinely mirrors your brand’s identity.',
    ],
    imageSrc: brandingDesigning768x587Image,
    altText: 'Branding Design Image',
    points: [
      'Creates a professional image',
      'Establish brand recognition',
      'Improves customer loyalty',
      'Increases brand value',
    ],
    pulseImageSrc: branding1Image,
    pulseAltText: 'Branding Pulse',
  },
  {
    id: 5,
    title: 'Branding and Marketing Designing Services in Bangalore',
    description: [
      'Our rigorous usability testing ensures our designs hit the mark. These tests allow us to identify potential issues early on and address them proactively, optimizing user satisfaction and overall platform performance.',
      'This commitment to quality and continuous improvement sets us apart as Bangalore’s best UX/UI design service.',
    ],
    imageSrc: businessAndMarketingDesign768x587Image,
    altText: 'Marketing Design Image',
    points: [
      'Better foundation',
      'Cost-effective brand campaigns',
      'Brand strategy',
      'Encourage word of mouth',
    ],
    pulseImageSrc: renameImage,
    pulseAltText: 'Rename Pulse',
  },
];
